# Build and deploy a Jekyll site to GitHub Pages
name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Nếu repo KHÔNG có Gemfile hoặc không thực sự là site Jekyll
      # (chỉ có test.html, ảnh, v.v.), thì nên bỏ qua bước build bằng Jekyll:
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
        continue-on-error: true   # tránh lỗi nếu không có Jekyll site

      - name: Copy static HTML if Jekyll not used
        run: |
          if [ ! -d "_site" ]; then mkdir _site; fi
          cp -r *.html *.jpg *.png image _site/ 2>/dev/null || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
